# Calculate the total revenue generated by each seller, and rank them by revenue.
SELECT 
    ecommerce.sellers.seller_id AS sellers,
    ROUND(SUM(ecommerce.payments.payment_value), 2) AS revenue
FROM
    ecommerce.sellers
        JOIN
    ecommerce.order_items ON ecommerce.sellers.seller_id = ecommerce.order_items.seller_id
        JOIN
    ecommerce.payments ON ecommerce.order_items.order_id = ecommerce.payments.order_id
GROUP BY sellers
ORDER BY revenue